### ISSUE TITLE
Implement Transform Tool

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#1253] opened 2023-04-27 09:59 UTC
Possibility to move/scale/rotate elements.

In the UI, this might be a subset of the Select Tool, but we track it as a separate GitHub issues since it may in the future be a separate tool, and the backend for transforming elements is quite unrelated to the backend for selecting elements.

**Comment by dalboris** [comment] 2023-05-04 17:02
Already implemented: drag move with linear transform of incident edges: #1284

**Comment by PixelRick** [comment] 2023-07-10 13:19
Duplicate of #1362.

**Closed by PixelRick** 2023-07-10 13:19 UTC
