### ISSUE TITLE
Python console starts with '...' instead of '>>>'

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#27] opened 2018-08-02 13:20 UTC
Currently, when I open the Python console, the command prompt is `...` instead of `>>>`. It fixes itself when interpreting the first block of code. Example session:
```
...
```
Type `1+1`
```
... 1+1
```
Press `<Enter>`
```
... 1+1
...
```
Type `1+1`
```
... 1+1
... 1+1
```
Press `<Ctrl-Enter>`
```
>>> 1+1
... 1+1
>>>
```

**Comment by myin142** [comment] 2018-11-29 17:29
In case the bug is still there. I found the cause of it. It is because at start `codeBlocks` has only the value 0 and lineNumber is also 0. So there is no upper bound and the function `vgc::core::upper_bound` return -1.

It can be fixed by adding

`if(codeBlockIndex < 0) codeBlockIndex = 0;`

or something similar to the `updateCodeBlockIndex_`. Not sure if it is the best way. But it is the best I could come up with.

**Closed as completed** 2018-11-29 20:26 UTC
Labels: bug
