### ISSUE TITLE
Appimages doesn't support pressure sensitivity.

### ISSUE THREAD

**Issue by ebarranco** [vgc/vgc#239] opened 2019-11-04 20:52 UTC
I tested the appimage file and pressure sensitivity is not working [I show you in this video.](https://youtu.be/p0uyx-W4YJ8)

**Comment by dalboris** [comment] 2019-11-04 21:14
Good catch, I should indeed have tested with something else than my mouse. What a bummer... it works nicely outside the AppImage. I have no clue what could be the problem, I'll have to investigate.

**Comment by dalboris** [comment] 2019-11-05 11:40
I still haven't fixed this, but I'm reporting some initial findings.

The bug was only with the appimage generated on TravisCI. With an appimage generated locally on one of my development machines, running Ubuntu 16.04, the bug wasn't there (i.e., pressure sensitivity works with the appimage generated locally).

Also, if I extract the appimage via `./travis.appimage --appimage-extract` and run the executable directly with `./travis.appimage/usr/bin/vgcillustration`, the bug is still there. Therefore, it's definitely not something related to being run inside an AppImage, but caused by the difference of libraries shipped when generated via TravisCI vs. generated on my local machine.

At first, I hoped it was simply just missing Qt plugins on the Travis AppImage. There are indeed more plugins deployed on my local machine for some reasons, but nothing *really*  suspicious:

```
# plugins on travis.appdir
./usr/plugins/imageformats/libqgif.so
./usr/plugins/imageformats/libqico.so
./usr/plugins/imageformats/libqjpeg.so
./usr/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
./usr/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
./usr/plugins/platforms/libqxcb.so
./usr/plugins/xcbglintegrations/libqxcb-glx-integration.so

# plugins on local.appdir
./usr/plugins/iconengines/libqsvgicon.so                                                                                               
./usr/plugins/imageformats/libqgif.so                                                                                                  
./usr/plugins/imageformats/libqicns.so                                                                                                 
./usr/plugins/imageformats/libqico.so                                                                                                  
./usr/plugins/imageformats/libqjpeg.so                                                                                                 
./usr/plugins/imageformats/libqsvg.so                                                                                                  
./usr/plugins/imageformats/libqtga.so                                                                                                  
./usr/plugins/imageformats/libqtiff.so                                                                                                 
./usr/plugins/imageformats/libqwbmp.so                                                                                                 
./usr/plugins/imageformats/libqwebp.so                                                                                                 
./usr/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so                                                            
./usr/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so                                                               
./usr/plugins/platforms/libqxcb.so                                                                                                     
./usr/plugins/xcbglintegrations/libqxcb-egl-integration.so                                                                             
./usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
 ```

I tried to use Meld to compare the two appdirs, and indeed there are different libraries shipped, but again, nothing really suspicious came out at a first glance.

But, then, I had the good idea to try the following:

```
$ grep -r "tablet" local.appdir/
Binary file nobug.appdir/usr/lib/libQt5Svg.so.5 matches
Binary file nobug.appdir/usr/lib/libvgcwidgets.so matches
Binary file nobug.appdir/usr/lib/libQt5Widgets.so.5 matches
Binary file nobug.appdir/usr/lib/libQt5XcbQpa.so.5 matches
Binary file nobug.appdir/usr/lib/libQt5Gui.so.5 matches

$ grep -r "tablet" travis.appdir/
Binary file bug.appdir/usr/lib/libvgcwidgets.so matches
Binary file bug.appdir/usr/lib/libQt5Widgets.so.5 matches
Binary file bug.appdir/usr/lib/libQt5Gui.so.5 matches
```

Aha!

Is `libQt5XcbQpa.so.5` missing in the Travis appimage? No, it's there, but it doesn't contain the word "tablet", and it is much smaller in size: 1.4MB instead of 2.2MB. So there seems to be differences between the Qt provided by [ppa:beineri/opt-qt-5.12.3-xenial](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.12.3-xenial) which I use on Travis, and the official Qt 5.12.3 build that I use on my machine.

(Note: Initially, I was in fact using Qt 5.12.5 on my local machine, but downgraded to Qt 5.12.3 to match the version used on Travis and there was the same behaviour: it worked locally and had a ~2.2MB libQt5XcbQpa.so.5)

So let's try with the beineri package on my local machine:

```
$ sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
$ sudo apt-get -y update
$ sudo apt-get install -y qt512base
$ mkdir vgc-build-beineri
$ cd vgc-build-beineri
$ source /opt/qt512/bin/qt512-env.sh
$ cmake ../vgc -DCMAKE_BUILD_TYPE=Release
$ make
$ ./Release/bin/vgcillustration
==> Bingo! I could reproduced the bug on a locally built VGC. No pressure sensitivity.
```

So there it is: the bug is caused by the [ppa:beineri/opt-qt-5.12.3-xenial](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.12.3-xenial) version of Qt, which for some reason seems not to include tablet pressure functionality. In conclusion, I'll probably have to package Qt myself and use this in my Travis builds.

**Comment by dalboris** [comment] 2019-11-05 16:37
@ebarranco I think it is now fixed! Can you try the following AppImage and let me know if it works for you too:

https://www.vgc.io/releases/pr/240/2019-11-05.3/vgcillustration-alpha-gh239a-2019-11-05.3-x86_64.AppImage

**Comment by ebarranco** [comment] 2019-11-05 17:25
Yes @dalboris pen pressure is working now. :champagne: Thanks for the fix.

**Comment by dalboris** [comment] 2019-11-05 17:37
Perfect!

**Closed by dalboris** 2019-11-05 17:37 UTC
